/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedactionRouteImport } from './routes/redaction'
import { Route as RedactionDocumentIdRouteImport } from './routes/redaction.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionRoute = RedactionRouteImport.update({
  id: '/redaction',
  path: '/redaction',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionDocumentIdRoute = RedactionDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => RedactionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redaction': typeof RedactionRouteWithChildren
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redaction': typeof RedactionRouteWithChildren
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redaction': typeof RedactionRouteWithChildren
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redaction' | '/redaction/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redaction' | '/redaction/$documentId'
  id: '__root__' | '/' | '/redaction' | '/redaction/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedactionRoute: typeof RedactionRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction': {
      id: '/redaction'
      path: '/redaction'
      fullPath: '/redaction'
      preLoaderRoute: typeof RedactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction/$documentId': {
      id: '/redaction/$documentId'
      path: '/$documentId'
      fullPath: '/redaction/$documentId'
      preLoaderRoute: typeof RedactionDocumentIdRouteImport
      parentRoute: typeof RedactionRoute
    }
  }
}

interface RedactionRouteChildren {
  RedactionDocumentIdRoute: typeof RedactionDocumentIdRoute
}

const RedactionRouteChildren: RedactionRouteChildren = {
  RedactionDocumentIdRoute: RedactionDocumentIdRoute,
}

const RedactionRouteWithChildren = RedactionRoute._addFileChildren(
  RedactionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedactionRoute: RedactionRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
