/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedactionIndexRouteImport } from './routes/redaction.index'
import { Route as RedactionDocumentIdRouteImport } from './routes/redaction.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionIndexRoute = RedactionIndexRouteImport.update({
  id: '/redaction/',
  path: '/redaction/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactionDocumentIdRoute = RedactionDocumentIdRouteImport.update({
  id: '/redaction/$documentId',
  path: '/redaction/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
  '/redaction/': typeof RedactionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
  '/redaction': typeof RedactionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redaction/$documentId': typeof RedactionDocumentIdRoute
  '/redaction/': typeof RedactionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/redaction/$documentId' | '/redaction/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redaction/$documentId' | '/redaction'
  id: '__root__' | '/' | '/redaction/$documentId' | '/redaction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedactionDocumentIdRoute: typeof RedactionDocumentIdRoute
  RedactionIndexRoute: typeof RedactionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction/': {
      id: '/redaction/'
      path: '/redaction'
      fullPath: '/redaction/'
      preLoaderRoute: typeof RedactionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redaction/$documentId': {
      id: '/redaction/$documentId'
      path: '/redaction/$documentId'
      fullPath: '/redaction/$documentId'
      preLoaderRoute: typeof RedactionDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedactionDocumentIdRoute: RedactionDocumentIdRoute,
  RedactionIndexRoute: RedactionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
