"""add otp_secret and is_otp_enabled to users

Revision ID: 568be2a4a33f
Revises: c2741e63d117
Create Date: 2026-08-02 12:41:57.537092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString


# revision identifiers, used by Alembic.
revision: str = "568be2a4a33f"
down_revision: Union[str, Sequence[str], None] = "c2741e63d117"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("otp_secret", AutoString(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_otp_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_otp_enabled")
    op.drop_column("users", "otp_secret")
    # ### end Alembic commands ###
